config:
  save_logout_world: true
debug-mode: true
permissions:
  comando-minas: comando.minas
  comando-dragon: comando.dragon
  comando-nether: comando.nether
  comando-parcelas: comando.parcelas
  comando-villa: comando.villa
messages:
  join: "&a▲ &7%player_name%"
  new-player: "&6&lUB> &f%player_name% &6Ha entrado por primera vez al servidor!"
commands:
  villa:
    - "[CONSOLE];spawn %player%"
  parcelas:
    - "[CONSOLE];customwarps warp parcelas %player%"
  parcelaswithplot:
    - "[PLAYER];p h"